[BACKLOG-15186]: PMR and Hadoop Job Executor job entries fail because of they can not find "LogWriter" class (NoClassDefFoundError)
Hadoop Job Executor job entry uses org.pentaho.di.core.logging.LogWriter. This is located in kettle5-log4j-plugin-xxx.jar.
This jar was pulled into <PENTAHO>\data-integration\lib transitively from pentaho-reporting-engine-classic-extensions-kettle project.
After GAV changes for reporting projects (https://github.com/pentaho/pentaho-kettle/commit/8136fd585deb77007d06a89a0df369cae83285c1) this jar stopped to be pulling out transitively
and disapeared from <PENTAHO>\data-integration\lib.

But we need to have it for big-data-project.
So the fix is to recieve this dependency directly.