[BACKLOG-33146] Update and validate in-product links in 9.0
[BACKLOG-33104] - Copyright needs to be updated to 2020 on 'Info.plist' for each client tool

[BACKLOG-33177] Updated big data driver directory's README file

[BACKLOG-33146] Change to VFS browser help url

[BACKLOG-33183] Disable copy/cut/paste

[BACKLOG-33158] Fixed bug where Windows was not opening path from URL a second time when accessing remote files

[BACKLOG-33158] Fixing sonar issues

Revert "[BACKLOG-33183] Disable copy/cut/paste" (#7215)

[BACKLOG-33243] Embedded webservices for VFS are exposed to external requests

[CLEANUP] updated versions via release version merger

Rebase onto 9.0.0.0-423

RAP does not implement Browser.setCookie and it may not be needed in webSpoon

Update 8.3 to 9.0 anywhere else

Fix a rebase mistake

Do not include the driver kar set in the war file

Add org.apache.karaf.specs.locator-4.2.6.jar otherwise NoClassDefFoundError happens during boot

java.lang.NoClassDefFoundError: org/apache/karaf/specs/locator/OsgiLocator

Update Selenium to 3.141.59

Remove duplicate WebSpoonFilter (fix #168)

Cleanup pom.xml

Adapt the ui test with the upstream change

Instruct how to install Hadoop drivers

Update CHANGELOG

Include static images and css

Change the path to the static images and css

Related to 80362a200f1276bf01c0dfe1bd444e10eed64a8e

Fix static images and css at jobStatus and transStatus too

Update webSpoon_OSS_Licenses

Patch file-open-save-new-core to fix the ThinDialog page loading

Fix file-open-save-new-core to make it fully-functional

Update CHANGELOG

WebSpoonUtils.setUISession after a test context is created (fix #192)

Update RAP/RWT to 3.12.0 (#194)

Update README and CHANGELOG about RAP/RWT update

[PPP-4459] Use of Vulnerable Component: org.eclipse.paho:org.eclipse.paho.client.mqttv3: CVE-2019-11777

Revert "[PPP-4459] Use of Vulnerable Component: org.eclipse.paho:org.eclipse.paho.client.mqttv3: CVE-2019-11777"

This reverts commit e67df8a0affd1fc99d23c6c15e0746b86f921287.

Make sure children get populated only once (fix #199)

A regression caused by 3c4116deb1ae6d052d998ae631a78ba359e71c52

Revert changes to StyledTextComp.java

Update CHANGELOG

Remove variables that are no longer used due to a55b60e9

These variables were
introduced by 71b441c0307cd112682e562832daf2099a8fdf76
modified   by 1d1d982f1f28e981af1b75422c6d21fc119a0039
abandoned  by a55b60e98aca47da6ff71ca5c2ee2339c79936ac

Revert some changes to LogBrowser.java as RAP/RWT now has the corresponding (emtpy) method

Update ISSUE_TEMPLATE

- Add a checklist
- Add Docker/non-Docker question at the server specs

Add a line break at the bullet list

Merge HiromuHota/webspoon-docker into HiromuHota/pentaho-kettle

Change current directory to "docker"

Adjust path to install.sh and slave-server-config.xml

Fix the path of slave-server-config.xml

Update version to 0.9.0.22 and README

Update Dockerfile

Released 0.9.0.22

Update version that was outdated to 0.9.0.22

[webspoon-9.0] First attempt to show LDOS tile

[webspoon-9.0] Implemented GitHub actions

[webspoon-9.0] Updated readme file

[webspoon-9.0] Updated helm charts

[CLEANUP] Target public runner

[webspoon-9.0] Updated helm charts

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[webspoon-9.0] Added pentaho-xul-swt to Github actions

[TAP-4108] Update to facilitate manual upload of webspoon helm chart to foundry (#7929)

[TAP-4108] sso changes to facilitate webspoon url (#7931)

Webspoon 9.0 (#7932)

* [TAP-4108] sso changes to facilitate webspoon url

* [TAP-4108] sso changes to facilitate webspoon url

Webspoon 9.0 (#7933)

* [TAP-4108] sso changes to facilitate webspoon url

* [TAP-4108] sso changes to facilitate webspoon url

* [TAP-4108] sso changes to facilitate webspoon url

[TAP-4108] sso changes to facilitate webspoon url (#7936)

[TAP-4108] sso changes to facilitate webspoon url

[TAP-4108] sso changes to facilitate webspoon url (#7937)

Webspoon 9.0 (#7946)

* [TAP-4108] sso changes to facilitate webspoon url

* Integrated Angels changes

* My changes to security

* Last best hack at getting this to work

[webspoon-9.0] SSO Fix

Webspoon 9.0 (#7950)

* [TAP-4108] sso changes to facilitate webspoon url

* Integrated Angels changes

* My changes to security

* Last best hack at getting this to work

* Added additional HTTP methods.

Webspoon 9.0 (#7961)

* [TAP-4108] sso changes to facilitate webspoon url

* Integrated Angels changes

* My changes to security

* Last best hack at getting this to work

* Added additional HTTP methods.

* [TAP-4242] - Added support for NFS save location

[webspoon-9.0] Added Vim and sudo to docker image

[webspoon-9.0] Rebase against master

[TAP-4397] Changes to build from Pentaho repos (#7973)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4397] Switched docker image build to maven assembly (#7977)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

Tap 4397 (#7978)

* [webspoon-9.0] TEST

* [TAP-4397] Rebase against 9.2.0.0

* [TAP-4397] Fixed some pom versions

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4397] Fixed eclipse rap version (#7985)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

Integrated Angels changes

My changes to security

Last best hack at getting this to work

[TAP-4242] - Added support for NFS save location

Local changes

[TAP-4311] - Added scripts for user defined configurations

[TAP-4311] - Fixed a problem with "WORKING_DIR" in scripts for user defined configurations

[DEVO-2092] Created a separate profile for docker assembly (#7995)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[DEVO-2092] Created a separate profile for kettle-core (#7996)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4561] Removed extra jface lib jar (#7998)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4398] WebSpoon Branch - Include Rap Repo

[TAP-4398] Rap extensions module moved into its own repo

[TAP-4471] Added big data drivers to DTE (#8011)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4389] WebSpoon Name Change

[TAP-4641] DTE - Hadoop Cluster's right click menu showing for other options

[TAP-4636] Fixed pull down menus (#8024)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4534] Changed RAP dependencies to 3.12.0.pentaho

[DEVO-2092] Fixed missing modules (#8027)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4730] - Removed Application URL from DTE card (#8029)

[TAP-4731] Circular Dependency between kettle UI SWT and Pentaho platform extension (#8033)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Removed pentaho-platform-core AND pentaho-platform-api dependencies (#8035)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Fix for "Failure to find org.pentaho.di.plugins:core-ui" (#8038)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Fix for "Failure to find org.pentaho.di.plugins:file-open-save-new-api" (#8039)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Failure to find org.pentaho.di.plugins:pdi-engine-configuration-impl (#8040)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Fix for "Failure to find org.pentaho.di.plugins:pdi-engine-configuration-api" (#8041)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Fix for "Could not find artifact org.pentaho.di.plugins:pdi-core-plugins-impl" (#8044)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Fix for "Could not find artifact org.pentaho.di.plugins:meta-inject-plugin" (#8046)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Reorder dependencies (#8047)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Fix for "Could not find artifact org.pentaho.di.plugins:kettle-json-plugin-core" (#8048)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Fix for Failure to find org.pentaho.di.plugins:pentaho-streaming-mqtt-plugin (#8049)

Co-authored-by: ezequiel <ezequiel.cuellar@gmail.com>

[TAP-4534] Fix for class file for org.eclipse.swt.widgets.IFileDialog not found

[TAP-4534] Fix for cannot access org.eclipse.swt.widgets.IFileDialog

[TAP-4534] Fix for org.pentaho.di:webspoon:pom:9.2.0.0-37: Failure to find org.pentaho.di:pdi-plugins:zip:

[TAP-4534] Restored pdi ce and ee client zips (#8057)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4824] Fixed Fixed Angular service base URL (#8063)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4423] DTE - 'Modified Java Script Value' step- Error on clicking OK

[CLEANUP] removing CodeQL action build

[CLEANUP] removing CodeQL action build

[TAP-4927] Restricted user browsing to user's home folder (#8085)

Co-authored-by: Angel Ramos <angel.ramos@hitachivantara.com>

[TAP-4927] - Restrict Http access to directory structure